import { Layer, LayerType, Color } from "@/types/canvas";

export interface TemplateDefinition {
  id: string;
  title: string;
  category: string;
  description: string;
  layers: Record<string, Layer>;
  layerIds: string[];
}

const colorSky: Color = { r: 39, g: 142, b: 237 };
const colorEmerald: Color = { r: 16, g: 185, b: 129 };
const colorViolet: Color = { r: 139, g: 92, b: 246 };
const colorAmber: Color = { r: 245, g: 158, b: 11 };
const colorRose: Color = { r: 243, g: 82, b: 35 };
const colorWhite: Color = { r: 255, g: 255, b: 255 };
const colorDark: Color = { r: 24, g: 24, b: 27 };

export const TEMPLATES: Record<string, TemplateDefinition> = {
  "system-design": {
    id: "system-design",
    title: "System Design",
    category: "Architecture",
    description: "URL Shortener distributed architecture with gateways, services, cache, and message queue",
    layerIds: [
      "sd-header",
      "sd-client",
      "sd-c1",
      "sd-gateway",
      "sd-c2",
      "sd-url-svc",
      "sd-auth-svc",
      "sd-analytics-svc",
      "sd-cache",
      "sd-db",
      "sd-queue",
    ],
    layers: {
      "sd-header": {
        type: LayerType.Text,
        x: 80,
        y: 40,
        width: 480,
        height: 48,
        fill: colorDark,
        value: "🏗️ System Design: Scalable URL Shortener",
        fontSize: 24,
        fontWeight: 700,
      },
      "sd-client": {
        type: LayerType.SystemShape,
        x: 80,
        y: 140,
        width: 140,
        height: 90,
        fill: colorSky,
        shapeKind: "Client",
        value: "Web & Mobile\nClients",
      },
      "sd-c1": {
        type: LayerType.ArrowConnector,
        x: 230,
        y: 180,
        width: 70,
        height: 10,
        fill: colorSky,
        arrow: true,
      },
      "sd-gateway": {
        type: LayerType.SystemShape,
        x: 310,
        y: 140,
        width: 150,
        height: 90,
        fill: colorViolet,
        shapeKind: "API Gateway",
        value: "API Gateway\nRate Limiter & SSL",
      },
      "sd-c2": {
        type: LayerType.ArrowConnector,
        x: 470,
        y: 180,
        width: 70,
        height: 10,
        fill: colorViolet,
        arrow: true,
      },
      "sd-url-svc": {
        type: LayerType.SystemShape,
        x: 550,
        y: 110,
        width: 150,
        height: 80,
        fill: colorEmerald,
        shapeKind: "Server",
        value: "URL Service\nEncode & Redirect",
      },
      "sd-auth-svc": {
        type: LayerType.SystemShape,
        x: 550,
        y: 210,
        width: 150,
        height: 80,
        fill: colorEmerald,
        shapeKind: "Server",
        value: "Auth Service\nJWT & API Keys",
      },
      "sd-analytics-svc": {
        type: LayerType.SystemShape,
        x: 550,
        y: 310,
        width: 150,
        height: 80,
        fill: colorEmerald,
        shapeKind: "Worker",
        value: "Analytics Worker\nClick Stream",
      },
      "sd-cache": {
        type: LayerType.SystemShape,
        x: 770,
        y: 110,
        width: 150,
        height: 80,
        fill: colorRose,
        shapeKind: "Cache",
        value: "Redis Cluster\nHot URL Cache",
      },
      "sd-db": {
        type: LayerType.SystemShape,
        x: 770,
        y: 210,
        width: 150,
        height: 80,
        fill: colorAmber,
        shapeKind: "Database",
        value: "PostgreSQL\nURL & User Store",
      },
      "sd-queue": {
        type: LayerType.SystemShape,
        x: 770,
        y: 310,
        width: 150,
        height: 80,
        fill: colorSky,
        shapeKind: "Queue",
        value: "Kafka Stream\nAsync Events",
      },
    },
  },

  "database-design": {
    id: "database-design",
    title: "Database Design",
    category: "SQL & Data",
    description: "E-Commerce database ER diagram with PK/FK columns and relational structure",
    layerIds: ["db-header", "tbl-users", "tbl-orders", "tbl-order-items", "tbl-products", "tbl-categories", "tbl-payments"],
    layers: {
      "db-header": {
        type: LayerType.Text,
        x: 80,
        y: 40,
        width: 480,
        height: 48,
        fill: colorDark,
        value: "🗄️ Database Design: E-Commerce ER Schema",
        fontSize: 24,
        fontWeight: 700,
      },
      "tbl-users": {
        type: LayerType.Table,
        x: 80,
        y: 120,
        width: 220,
        height: 180,
        fill: colorSky,
        value: "USERS\n[PK] id: INT\nname: VARCHAR(100)\nemail: VARCHAR(255) UNIQUE\ncreated_at: TIMESTAMP",
      },
      "tbl-orders": {
        type: LayerType.Table,
        x: 350,
        y: 120,
        width: 230,
        height: 190,
        fill: colorEmerald,
        value: "ORDERS\n[PK] id: INT\n[FK] user_id: INT -> Users\ntotal_cents: INT\nstatus: VARCHAR(30)\ncreated_at: TIMESTAMP",
      },
      "tbl-order-items": {
        type: LayerType.Table,
        x: 630,
        y: 120,
        width: 240,
        height: 190,
        fill: colorViolet,
        value: "ORDER_ITEMS\n[PK] id: INT\n[FK] order_id: INT -> Orders\n[FK] product_id: INT -> Products\nquantity: INT\nunit_price: INT",
      },
      "tbl-products": {
        type: LayerType.Table,
        x: 630,
        y: 350,
        width: 240,
        height: 180,
        fill: colorAmber,
        value: "PRODUCTS\n[PK] id: INT\n[FK] category_id: INT -> Categories\ntitle: VARCHAR(200)\nprice_cents: INT\nstock: INT",
      },
      "tbl-categories": {
        type: LayerType.Table,
        x: 350,
        y: 350,
        width: 230,
        height: 160,
        fill: colorRose,
        value: "CATEGORIES\n[PK] id: INT\nname: VARCHAR(80)\nslug: VARCHAR(100) UNIQUE\nparent_id: INT NULL",
      },
      "tbl-payments": {
        type: LayerType.Table,
        x: 80,
        y: 350,
        width: 220,
        height: 170,
        fill: colorSky,
        value: "PAYMENTS\n[PK] id: INT\n[FK] order_id: INT -> Orders\namount_cents: INT\nprovider: VARCHAR(40)\nstatus: VARCHAR(30)",
      },
    },
  },

  "code-review": {
    id: "code-review",
    title: "Code Review",
    category: "Development",
    description: "Code review board with code block, reviewer sticky notes, and triage categories",
    layerIds: ["cr-header", "cr-code", "cr-reviewer", "cr-bugs", "cr-perf", "cr-security", "cr-suggestions"],
    layers: {
      "cr-header": {
        type: LayerType.Text,
        x: 80,
        y: 40,
        width: 480,
        height: 48,
        fill: colorDark,
        value: "💻 Code Review: Auth API & Session Validation",
        fontSize: 24,
        fontWeight: 700,
      },
      "cr-code": {
        type: LayerType.Code,
        x: 80,
        y: 110,
        width: 460,
        height: 240,
        fill: colorDark,
        language: "typescript",
        value: `export async function loginUser(req: Request) {
  const { email, password } = await req.json();
  const user = await db.user.findUnique({ where: { email } });
  
  // FIXME: Plaintext comparison!
  if (!user || user.password !== password) {
    return new Response("Unauthorized", { status: 401 });
  }

  return Response.json({ token: signToken(user.id) });
}`,
      },
      "cr-reviewer": {
        type: LayerType.Note,
        x: 580,
        y: 110,
        width: 240,
        height: 240,
        fill: colorRose,
        value: "💬 Reviewer: @security-team\n\n🚨 CRITICAL SECURITY FLAW:\nUser passwords cannot be matched in plaintext!\n\nMust use:\nawait bcrypt.compare(\n  password,\n  user.passwordHash\n)\n\nAlso wrap in try/catch for JSON syntax errors.",
      },
      "cr-bugs": {
        type: LayerType.Note,
        x: 80,
        y: 380,
        width: 200,
        height: 180,
        fill: colorRose,
        value: "🐛 Bugs\n\n• Missing error handling if req body is empty\n• Return 400 on invalid email shape",
      },
      "cr-perf": {
        type: LayerType.Note,
        x: 310,
        y: 380,
        width: 200,
        height: 180,
        fill: colorAmber,
        value: "⚡ Performance\n\n• Cache validated session in Redis for 15m\n• Add DB index on user.email",
      },
      "cr-security": {
        type: LayerType.Note,
        x: 540,
        y: 380,
        width: 200,
        height: 180,
        fill: colorViolet,
        value: "🔐 Security\n\n• Rate-limit login: 5 req/min per IP\n• Use HttpOnly secure cookies\n• Log auth failures to SIEM",
      },
      "cr-suggestions": {
        type: LayerType.Note,
        x: 770,
        y: 380,
        width: 200,
        height: 180,
        fill: colorEmerald,
        value: "✨ Suggestions\n\n• Use Zod schema validation\n• Add integration tests with mock DB",
      },
    },
  },

  "mind-map": {
    id: "mind-map",
    title: "Mind Map",
    category: "Learning",
    description: "DSA Roadmap mind map with central topic and branches for Arrays, Trees, and Graphs",
    layerIds: [
      "mm-header",
      "mm-center",
      "mm-c-arrays",
      "mm-node-arrays",
      "mm-arr-sub1",
      "mm-arr-sub2",
      "mm-c-trees",
      "mm-node-trees",
      "mm-tree-sub1",
      "mm-tree-sub2",
      "mm-c-graphs",
      "mm-node-graphs",
      "mm-graph-sub1",
      "mm-graph-sub2",
    ],
    layers: {
      "mm-header": {
        type: LayerType.Text,
        x: 80,
        y: 40,
        width: 480,
        height: 48,
        fill: colorDark,
        value: "🧠 Mind Map: Data Structures & Algorithms Roadmap",
        fontSize: 24,
        fontWeight: 700,
      },
      "mm-center": {
        type: LayerType.Reactangle,
        x: 440,
        y: 240,
        width: 160,
        height: 70,
        fill: colorViolet,
        value: "DSA Core\nRoadmap",
      },
      "mm-c-arrays": {
        type: LayerType.Connector,
        x: 320,
        y: 190,
        width: 120,
        height: 60,
        fill: colorSky,
      },
      "mm-node-arrays": {
        type: LayerType.Reactangle,
        x: 180,
        y: 150,
        width: 140,
        height: 60,
        fill: colorSky,
        value: "Arrays & Strings",
      },
      "mm-arr-sub1": {
        type: LayerType.Ellipse,
        x: 40,
        y: 110,
        width: 120,
        height: 50,
        fill: colorSky,
        value: "Two Pointer",
      },
      "mm-arr-sub2": {
        type: LayerType.Ellipse,
        x: 40,
        y: 180,
        width: 120,
        height: 50,
        fill: colorSky,
        value: "Sliding Window",
      },
      "mm-c-trees": {
        type: LayerType.Connector,
        x: 600,
        y: 190,
        width: 120,
        height: 60,
        fill: colorEmerald,
      },
      "mm-node-trees": {
        type: LayerType.Reactangle,
        x: 720,
        y: 150,
        width: 140,
        height: 60,
        fill: colorEmerald,
        value: "Trees & BST",
      },
      "mm-tree-sub1": {
        type: LayerType.Ellipse,
        x: 880,
        y: 110,
        width: 120,
        height: 50,
        fill: colorEmerald,
        value: "DFS Traversal",
      },
      "mm-tree-sub2": {
        type: LayerType.Ellipse,
        x: 880,
        y: 180,
        width: 120,
        height: 50,
        fill: colorEmerald,
        value: "BFS Level Order",
      },
      "mm-c-graphs": {
        type: LayerType.Connector,
        x: 510,
        y: 310,
        width: 30,
        height: 90,
        fill: colorAmber,
      },
      "mm-node-graphs": {
        type: LayerType.Reactangle,
        x: 440,
        y: 400,
        width: 160,
        height: 60,
        fill: colorAmber,
        value: "Graphs & Dynamic Prog.",
      },
      "mm-graph-sub1": {
        type: LayerType.Ellipse,
        x: 280,
        y: 480,
        width: 140,
        height: 50,
        fill: colorAmber,
        value: "Dijkstra & BFS",
      },
      "mm-graph-sub2": {
        type: LayerType.Ellipse,
        x: 480,
        y: 480,
        width: 140,
        height: 50,
        fill: colorAmber,
        value: "0/1 Knapsack DP",
      },
    },
  },

  "study-planner": {
    id: "study-planner",
    title: "Study Planner",
    category: "Productivity",
    description: "7-Day Technical Interview preparation schedule with daily goals and progress tracker",
    layerIds: ["sp-header", "sp-mon", "sp-tue", "sp-wed", "sp-thu", "sp-fri", "sp-weekend", "sp-progress"],
    layers: {
      "sp-header": {
        type: LayerType.Text,
        x: 80,
        y: 40,
        width: 520,
        height: 48,
        fill: colorDark,
        value: "📚 Study Planner: 7-Day SDE Interview Sprint",
        fontSize: 24,
        fontWeight: 700,
      },
      "sp-mon": {
        type: LayerType.Note,
        x: 80,
        y: 110,
        width: 200,
        height: 230,
        fill: colorSky,
        value: "📅 MONDAY\nArrays & Two Pointers\n\n☑ Two Sum (LC 1)\n☑ 3Sum (LC 15)\n☑ Trapping Rainwater (LC 42)\n\n⏱ Goal: 3 hours",
      },
      "sp-tue": {
        type: LayerType.Note,
        x: 300,
        y: 110,
        width: 200,
        height: 230,
        fill: colorEmerald,
        value: "📅 TUESDAY\nSliding Window & HashMaps\n\n☑ Longest Substring (LC 3)\n☑ Minimum Window (LC 76)\n☑ Group Anagrams (LC 49)\n\n⏱ Goal: 3 hours",
      },
      "sp-wed": {
        type: LayerType.Note,
        x: 520,
        y: 110,
        width: 200,
        height: 230,
        fill: colorViolet,
        value: "📅 WEDNESDAY\nLinked Lists & Fast/Slow\n\n☑ Reverse Linked List (LC 206)\n☑ Merge K Sorted Lists (LC 23)\n☑ LRU Cache (LC 146)\n\n⏱ Goal: 3 hours",
      },
      "sp-thu": {
        type: LayerType.Note,
        x: 740,
        y: 110,
        width: 200,
        height: 230,
        fill: colorAmber,
        value: "📅 THURSDAY\nBinary Trees & BST\n\n☑ Invert Binary Tree (LC 226)\n☑ Validate BST (LC 98)\n☑ Diameter of Tree (LC 543)\n\n⏱ Goal: 3 hours",
      },
      "sp-fri": {
        type: LayerType.Note,
        x: 80,
        y: 360,
        width: 200,
        height: 210,
        fill: colorRose,
        value: "📅 FRIDAY\nGraphs & BFS/DFS\n\n☑ Number of Islands (LC 200)\n☑ Clone Graph (LC 133)\n☑ Course Schedule (LC 207)\n\n⏱ Goal: 3.5 hours",
      },
      "sp-weekend": {
        type: LayerType.Note,
        x: 300,
        y: 360,
        width: 200,
        height: 210,
        fill: colorSky,
        value: "🎯 WEEKEND\nMock Interviews & System Design\n\n☑ 2 Peer Mocks on Pramp\n☑ URL Shortener Architecture\n☑ Review weak problem areas",
      },
      "sp-progress": {
        type: LayerType.Table,
        x: 520,
        y: 360,
        width: 420,
        height: 210,
        fill: colorWhite,
        value: "SPRINT PROGRESS TRACKER\nArrays & Strings:    [██████████] 100%\nLinked Lists:        [████████░░]  80%\nTrees & BST:         [██████░░░░]  60%\nGraphs:              [████░░░░░░]  40%\nSystem Design:       [██████░░░░]  60%",
      },
    },
  },

  "lecture-notes": {
    id: "lecture-notes",
    title: "Lecture Notes",
    category: "Academic",
    description: "Structured computer networks lecture notes with OSI model, concepts, and review questions",
    layerIds: ["ln-header", "ln-topic", "ln-osi", "ln-tcp-udp", "ln-questions", "ln-diagram"],
    layers: {
      "ln-header": {
        type: LayerType.Text,
        x: 80,
        y: 40,
        width: 520,
        height: 48,
        fill: colorDark,
        value: "📝 Lecture Notes: Computer Networks & OSI Model",
        fontSize: 24,
        fontWeight: 700,
      },
      "ln-topic": {
        type: LayerType.Note,
        x: 80,
        y: 110,
        width: 240,
        height: 220,
        fill: colorSky,
        value: "📌 TOPIC OVERVIEW\nCourse: CS 455 - Distributed Networks\nLecture: Protocol Stacks & Sockets\nDate: Week 4\n\nCore Goal: Understand how data moves from application buffer to physical copper/fiber.",
      },
      "ln-osi": {
        type: LayerType.Table,
        x: 340,
        y: 110,
        width: 320,
        height: 220,
        fill: colorWhite,
        value: "💡 7-LAYER OSI MODEL\n7. Application  -> HTTP, WebSocket, DNS\n6. Presentation -> SSL/TLS, JSON\n5. Session      -> RPC, Sessions\n4. Transport    -> TCP (Reliable), UDP\n3. Network      -> IP Addressing, Routers\n2. Data Link    -> Ethernet, MAC Addresses\n1. Physical     -> Bits, Cables, Radio",
      },
      "ln-tcp-udp": {
        type: LayerType.Note,
        x: 680,
        y: 110,
        width: 250,
        height: 220,
        fill: colorAmber,
        value: "⭐ TCP vs UDP COMPARISON\n\nTCP:\n• Connection-oriented (SYN, SYN-ACK, ACK)\n• Reliable: Guarantees ordering & retransmissions\n• Flow & Congestion Control\n\nUDP:\n• Connectionless & lightweight\n• Used for DNS, VoIP, Live Gaming",
      },
      "ln-questions": {
        type: LayerType.Note,
        x: 80,
        y: 350,
        width: 380,
        height: 210,
        fill: colorEmerald,
        value: "❓ EXAM REVIEW QUESTIONS\n\n1. Why does TCP use a 3-way handshake instead of a 2-way handshake?\n   -> To prevent old duplicate SYN packets from opening phantom connections.\n\n2. What is the difference between Flow Control (sliding window) and Congestion Control (CWND)?\n\n3. Why is DNS primarily run over UDP port 53?",
      },
      "ln-diagram": {
        type: LayerType.Reactangle,
        x: 480,
        y: 350,
        width: 450,
        height: 210,
        fill: colorViolet,
        value: "HTTP Request Lifecycle\n\nClient Browser\n      │  1. DNS Lookup (UDP 53)\n      ↓\nDNS Resolver ──→ Returns IP\n      │\n      │  2. TCP 3-Way Handshake (SYN -> SYN/ACK -> ACK)\n      │  3. TLS Handshake (ClientHello, Certificate, Key Exchange)\n      ↓\nWeb Server (Returns HTTP 200 OK + Payload)",
      },
    },
  },
};

export function getTemplateLayers(templateKey?: string): TemplateDefinition | null {
  if (!templateKey) return null;
  const normalized = templateKey.toLowerCase().replace(/[\s_]+/g, "-");
  return TEMPLATES[normalized] || null;
}
